stable-diffusion-1.5:
   description: Stable Diffusion version 1.5 diffusers model (4.27 GB)
   repo_id: runwayml/stable-diffusion-v1-5
   format: diffusers
   vae:
     repo_id: stabilityai/sd-vae-ft-mse
   recommended: True
   default: True
inpainting-1.5:
  description: RunwayML SD 1.5 model optimized for inpainting, diffusers version (4.27 GB)
  repo_id: runwayml/stable-diffusion-inpainting
  format: diffusers
  vae:
    repo_id: stabilityai/sd-vae-ft-mse
  recommended: True
dreamlike-diffusion-1.0:
  description: An SD 1.5 model fine tuned on high quality art by dreamlike.art, diffusers version (2.13 GB)
  format: diffusers
  repo_id: dreamlike-art/dreamlike-diffusion-1.0
  vae:
     repo_id: stabilityai/sd-vae-ft-mse
  recommended: True
dreamlike-photoreal-2.0:
  description: A photorealistic model trained on 768 pixel images based on SD 1.5 (2.13 GB)
  format: diffusers
  repo_id: dreamlike-art/dreamlike-photoreal-2.0
  recommended: False
stable-diffusion-2.1-768:
   description: Stable Diffusion version 2.1 diffusers model, trained on 768 pixel images (5.21 GB)
   repo_id: stabilityai/stable-diffusion-2-1
   format: diffusers
   recommended: True
stable-diffusion-2.1-base:
   description: Stable Diffusion version 2.1 diffusers base model, trained on 512 pixel images (5.21 GB)
   repo_id: stabilityai/stable-diffusion-2-1-base
   format: diffusers
   recommended: False
openjourney-4.0:
  description: An SD 1.5 model fine tuned on Midjourney images by PromptHero - include "mdjrny-v4 style" in your prompts (2.13 GB)
  format: diffusers
  repo_id: prompthero/openjourney
  vae:
     repo_id: stabilityai/sd-vae-ft-mse
  recommended: False
nitro-diffusion-1.0:
   description: A SD 1.5 model trained on three artstyles - prompt with "archer style", "arcane style" and/or "modern disney style" (2.13 GB)
   repo_id: nitrosocke/Nitro-Diffusion
   format: diffusers
   vae:
     repo_id: stabilityai/sd-vae-ft-mse
   recommended: False
trinart-2.0:
   description: An SD model finetuned with ~40,000 assorted high resolution manga/anime-style pictures, diffusers version (2.13 GB)
   repo_id: naclbit/trinart_stable_diffusion_v2
   format: diffusers
   vae:
     repo_id: stabilityai/sd-vae-ft-mse
   recommended: False
trinart-characters-2_0:
   description: An SD model finetuned with 19.2M anime/manga style images (ckpt version) (4.27 GB)
   repo_id: naclbit/trinart_derrida_characters_v2_stable_diffusion
   config: v1-inference.yaml
   file: derrida_final.ckpt
   format: ckpt
   vae:
      repo_id: naclbit/trinart_derrida_characters_v2_stable_diffusion
      file: autoencoder_fix_kl-f8-trinart_characters.ckpt
   width: 512
   height: 512
   recommended: False
ft-mse-improved-autoencoder-840000:
   description: StabilityAI improved autoencoder fine-tuned for human faces. Improves legacy .ckpt models (335 MB)
   repo_id: stabilityai/sd-vae-ft-mse-original
   format: ckpt
   config: VAE/default
   file: vae-ft-mse-840000-ema-pruned.ckpt
   width: 512
   height: 512
   recommended: True
trinart_vae:
   description: Custom autoencoder for trinart_characters for legacy .ckpt models only (335 MB)
   repo_id: naclbit/trinart_characters_19.2m_stable_diffusion_v1
   config: VAE/trinart
   format: ckpt
   file: autoencoder_fix_kl-f8-trinart_characters.ckpt
   width: 512
   height: 512
   recommended: False
